source 'https://cdn.cocoapods.org'

target 'iosApp' do
  use_frameworks!
  platform :ios, '15.5'
  pod 'composeApp', :path => '../composeApp'
end

# needed because of boringssl-grpc unsupported option '-g' for target
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
